SELECT FACULTY_NAME,COUNT(DISTINCT TEACHER_NAME) from FACULTY,TEACHER,PULPIT 
where "FACULTY"."FACULTY"="PULPIT"."FACULTY" AND "PULPIT"."PULPIT"="TEACHER"."PULPIT"
GROUP BY FACULTY_NAME 
ORDER BY COUNT(DISTINCT TEACHER_NAME) ASC;