SELECT TEACHER_NAME,FACULTY_NAME from FACULTY,TEACHER,PULPIT 
where "FACULTY"."FACULTY"="PULPIT"."FACULTY" AND "PULPIT"."PULPIT"="TEACHER"."PULPIT"
GROUP BY TEACHER_NAME,FACULTY_NAME
ORDER BY TEACHER_NAME;